Collecting FuzzyTM
  Using cached FuzzyTM-2.0.9-py3-none-any.whl.metadata (7.9 kB)
Requirement already satisfied: numpy in c:\users\vitto\anaconda3\lib\site-packages (from FuzzyTM) (1.26.4)
Requirement already satisfied: pandas in c:\users\vitto\anaconda3\lib\site-packages (from FuzzyTM) (1.4.4)
Requirement already satisfied: scipy in c:\users\vitto\anaconda3\lib\site-packages (from FuzzyTM) (1.10.1)
Collecting pyfume (from FuzzyTM)
  Using cached pyFUME-0.3.4-py3-none-any.whl.metadata (9.7 kB)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\vitto\anaconda3\lib\site-packages (from pandas->FuzzyTM) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\vitto\anaconda3\lib\site-packages (from pandas->FuzzyTM) (2024.1)
Collecting numpy (from FuzzyTM)
  Using cached numpy-1.24.4-cp39-cp39-win_amd64.whl.metadata (5.6 kB)
Collecting simpful==2.12.0 (from pyfume->FuzzyTM)
  Using cached simpful-2.12.0-py3-none-any.whl.metadata (4.8 kB)
Collecting fst-pso==1.8.1 (from pyfume->FuzzyTM)
  Using cached fst-pso-1.8.1.tar.gz (18 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
